routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// login google
// Route::get('/redirect', 'Auth\LoginController@redirectToProvider');
// Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

//login facebook
Route::get('/redirect', 'Auth\SocialAuthFacebookController@redirect');
Route::get('/callback', 'Auth\SocialAuthFacebookController@callback');

// Route::post('login', 'API\UserController@login');
// Route::post('register', 'API\UserController@register');

// Route::group(['middleware' => 'auth:api'], function(){
//     Route::post('details', 'API\UserController@details');
// });

Route::get('/', function(){
    return view ('welcome');
    if(\Auth::check()){
    	return \Redirect::to('/home');

    }
    return \Redirect::to('/login');


});


/* Expenses */
Route::resource('expenses', 'ExpensesController');


/* Category */
Route::resource('category', 'CategoryController');



/* Daily */

Route::get('daily','ByDateController@daily');
Route::post('daily','ByDateController@daily_filter');

/* Weekly */
Route::get('weekly','ByDateController@weekly');
Route::post('weekly','ByDateController@weekly_filter');

/* Monthly */
Route::get('monthly','ByDateController@monthly');
Route::post('monthly','ByDateController@monthly_filter');

/* Yearly */
Route::get('yearly','ByDateController@yearly');
Route::post('yearly','ByDateController@yearly_filter');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/content/categories.blade.php
@extends('master_layout.master')
    @section('content')

        <h3>Categories</h3>
        <hr>

        @foreach ($datas as $data)
            <div>{{ $data->title }}</div>
        @endforeach

        
    @endsection

resources/views/content/daily.blade.php
@extends('master_layout.master')
@section('content')
    @php
        $current_date = Carbon\Carbon::now()->toDateString();
    @endphp
    
    <div class="form-group">
        <label for="" class="font-weight-bold">Date</label>
        <input name="daily" class="form-control datepicker" id="daily" value="{{$current_date }}" date-date-format="yy-mm-dd"> 
       
    </div>
    <div id="result">

    </div>

    
@endsection

@section('sidebar')
    <canvas id="myChart" width="400" height="250"></canvas>
@endsection

@section('script')

    <script>
        $.extend({
            list: function(){
                $.post('/daily',{_token: $('meta[name=csrf-token]').attr('content'), daily:$('#daily').val()},function(data){
                   
                    console.log(data[0])
                    if (data[0].length == 0) {
                        $("#result").html('No Records Found');
                        $("#result").attr('class','alert alert-info');
                        $("#myChart").css('display','none');
                    
                    }else{

                        $("#result").removeAttr('class');
                        $("#myChart").css('display','') ;

                        if(data[0].length > 10){
                            $("#result").addClass('scroll');
                        }

                        var content;
                        content += '<tbody>'
                        $.each(data[0], function(i, val){

                             
                            content+='<tr>';
                            content += '<td>'+val.date+'</td>';
                            content += '<td >'+val.category.title+'</td>';
                            content += '<td >'+val.item+'</td>';
                            content += '<td >'+val.details+'</td>';
                            content += '<td >'+val.price+'</td>';
                            content+='</tr>'; 
                        
                        });
                        content += '</tbody>'
                       
                        var html = '<tr><th>Date</th><th>Category</th><th>Item</th><th>Details</th><th>Price</th>';

                        html+= '</tr>';
                        
                        $('#result').html('<table class="table shadow-lg"></table>');
                        $(".table").html(html);
                        $(".table").append(content);


                        //chart

                        var data = data[1];
                        var price = [];
                        var title = [];
                        var total = 0;
                       
                        for(var i = 0;  i < data.length; i++) {
                            title.push([data[i]['category']['title']]);
                            price.push([data[i]['price']]);
                            total += data[i]['price'] << 0; //convert the string elements to numerics using '<< 0'

                        }
                     
                        
                        var ctx = document.getElementById("myChart");
                        ctx.width = 500;
                        ctx.height = 400;
                        var myChart = new Chart(ctx, {
                            type: 'pie',
                            data: {
                                labels: title,
                                datasets: [{
                                    data: price,
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 0.2)',
                                        'rgba(54, 162, 235, 0.2)',
                                        'rgba(255, 206, 86, 0.2)',
                                        'rgba(75, 192, 192, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(255, 159, 64, 0.2)'
                                    ],

                                    borderWidth: 1,
                                    fontColor: '#666'


                                }]
                            },
                            options: {

                                title: {
                                    display: true,
                                    text: 'Day Total Expenses: '+total,
                                    fontSize: 25,
                                    padding: 20


                                },
                                tooltips:{
                                    enable: true,
                                    bodyFontSize: 20
                                },
                                legend:{
                                    display: true,
                                    position: 'right',
                                    labels:{
                                        fontSize: 10,
                                        fontColor: '#000'
                                    }
                                },
                                layout: {
                                    padding: {
                                        left: 0,
                                        right: 0,
                                        top: 20,
                                        bottom: 20
                                    }
                                }


                            }

                        });
                                    

                    }//else end  

               });    
            }
            
        });
        
    </script>
    <script>
        $.list();
        $('#daily').change(function(){
            $.list();
        });
       
    </script>
   
@endsection

resources/views/content/income.blade.php
@php
    $date = Carbon\Carbon::now();
    $expenses = App\Expenses::whereMonth('date', $date)->whereYear('date', $date)->where('status','active')->sum('price');

    $incomes = App\Income::with(['calendar' => function ($query) {
        $now = Carbon\Carbon::now();
        $y = $now->format('Y');
        $m = $now->format('M');

        $query->where( [['month',  $m],['year', $y]]);
    }])->get();

    foreach ($incomes as $income) {
        # code...
    }

@endphp
<ul id="income-list">
    <li>
        <p>INCOME</p>

    </li>
    <li >
       
        <span id="income-month">{{ $income->calendar->month }}</span> <span id="income-year">{{ $income->calendar->year }}</span>: 
       <span id="income_">${{ $income->income }}</span> <input type="hidden" class="income-input" value="{{  $income->income  }}">
      
      
    </li>
    <li >
        Expenses: ${{ $expenses }}

    </li>
   
</ul>
@section('script')

<script type="text/javascript">
    $(document).ready(function(){

        $("#income-list li:p").click(function() {
            alert('dsasd');
       
        });

    });
    
</script>
    


@endsection

resources/views/content/index.blade.php
@extends('master_layout.master')
@section('content')
   
    <button type="button" class="btn btn-success shadow-lg " data-toggle="modal" data-target="#exampleModal">
        <i class="fas fa-plus-circle"></i> Add item
    </button>
    
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                {{--  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add item</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>  --}}
                <div class="modal-body">
                    <form class="add_record" method="post" action="/expenses">
                        @csrf
                        @php
                            $current_date = Carbon\Carbon::now()->toDateString();
                        @endphp

                        <div class="form-group">
                            <label for="">Date</label>
                            <input name="date" class="form-control datepicker" id="datepicker" value="{{$current_date }}" date-date-format="yy-mm-dd" required>

                            {{--  <small id="item_small" class="form-text text-muted">Select the date of expenses.</small>  --}}
                        </div>
                        <div class="form-group">
                            <label for="">Category</label>
                            <select class="form-control" name="category" value="{{ old('category') }}" required autofocus>
                                <option selected disabled>Select Category</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                                @endforeach

                            </select>
                            @if ($errors->has('category'))
                                <small id="item_small" class="text-danger">{{ $errors->first('category') }}</small>

                            @endif

                        </div>

                        <div class="form-group">
                            <label for="">Item</label>
                            <input type="text" class="form-control" id="item" name="item" value="{{ old('item') }}" autofocus>
                            @if ($errors->has('item'))
                                <small id="item_small" class="text-danger">{{ $errors->first('item') }}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="">Details</label>
                            <input type="text" class="form-control" id="details" name="details" value="{{ old('details') }}" autofocus>
                            @if ($errors->has('details'))
                                <small id="item_small" class="text-danger">{{ $errors->first('details') }}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="">Price</label>
                            <input type="number" class="form-control" id="price" name="price" value="{{ old('price') }}" autofocus>
                            @if ($errors->has('price'))
                                <small id="item_small" class="text-danger">{{ $errors->first('price') }}</small>
                            @endif
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <table class="table shadow-lg">
        <thead>
            <th>Date</th>
            <th>Category</th>
            <th>Item</th>
            <th>Details</th>
            <th>Amount</th>
        </thead>
        <tbody>
            @foreach ($expenses as $expense)
                <tr class=" " >
                    <td><a href="{{ route('expenses.show',$expense->id)}}">{{ $expense->date }}</a></td>
                    <td><a href="{{ route('expenses.show',$expense->id)}}">{{ $expense->category->title }}</td>
                    <td><a href="{{ route('expenses.show',$expense->id)}}">{{ $expense->item }}</td>
                    <td><a href="{{ route('expenses.show',$expense->id)}}">{{ $expense->details }}</td>
                    <td><a href="{{ route('expenses.show',$expense->id)}}">{{ $expense->price }}</td>

                </tr>
            @endforeach
        </tbody>
    </table>
    <br><br>
    {{ $expenses->links() }}
@endsection

@section('sidebar')
    <canvas id="myChart" width="400" height="250"></canvas>
@endsection

@section('script')
    <script>
      
        // $("#table").delegate("tr", "click", function(){
        //     alert("Click!");
        // });
    </script>
   
    <script >
        @if(count($errors) > 0)
            $('#exampleModal').modal('show')                  
        @endif
    </script>
    <script>
        var data = @json($charts);
        var price = [];
        var title = [];
        var total = 0;
        for(var i = 0;  i < data.length; i++) {
            title.push([data[i]['category']['title']]);
            price.push([data[i]['price']]);
            total += data[i]['price'] << 0; //convert the string elements to numerics using '<< 0'

        }
        

        var ctx = document.getElementById("myChart");
        ctx.width = 500;
        ctx.height = 400;
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: title,
                datasets: [{
                    data: price,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],

                    borderWidth: 1,
                    fontColor: '#666'


                }]
            },
            options: {

                title: {
                    display: true,
                    text: 'Total Expenses '+total,
                    fontSize: 25,
                    padding: 20


                },
                tooltips:{
                    enable: true,
                    bodyFontSize: 20
                },
                legend:{
                    display: true,
                    position: 'right',
                    labels:{
                        fontSize: 10,
                        fontColor: '#000'
                    }
                },
                layout: {
                    padding: {
                        left: 0,
                        right: 0,
                        top: 20,
                        bottom: 20
                    }
                }


            }

        });
    </script>
    {{--  <script type="text/javascript">
         $('.add_record').on('submit', function() {
           
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                type: 'POST',
                url: '/expenses',
                data:  new FormData(this),
                dataType: 'json',
                contentType: false,
                cache: false,
                processData:false,
                success: function(data) {
                  
                       
                    $('#table').append("<tr class='item" + data.id + "'><td>" + data.date + "</td><td>" + data.item + "</td><td>" + data.details + "</td><td>" + data.price + "</td>");
                      
                 
                },   
                
            });
        });
       
       
    </script>  --}}
@endsection

resources/views/content/monthly.blade.php
@extends('master_layout.master')
@section('content')
    @php
        $current_date = Carbon\Carbon::now()->toDateString();
    @endphp
    <div class="row">
        <div class="form-group col-md-6">
            <label for="" class="font-weight-bold">Month</label>
            <select name="month" id="monthly" class="form-control">
                @php
                    for ($x=1; $x<=12; $x++) {
                        echo '<option value="'.$x.'">'.date('F',mktime(0,0,0,$x,1,date('Y'))).'</option>';
                    }
                @endphp

            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="" class="font-weight-bold">Year</label>
            <select name="year" id="month-year" class="form-control">
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
            </select>
        </div>
    </div>

    <div id="result">

    </div>

@endsection

@section('sidebar')
    <canvas id="myChart" width="400" height="250"></canvas>
@endsection

@section('script')

    <script>
        $.extend({
            list: function(){
                $.post('/monthly',{_token: $('meta[name=csrf-token]').attr('content'), month:$('#monthly').val(), year:$('#month-year').val()},function(data){

                  
                    if (data[0].length == 0) {
                        $("#result").html('No Records Found');
                        $("#result").attr('class','alert alert-info');
                        $("#myChart").css('display','none');

                    }else{

                        $("#result").removeAttr('class');
                        $("#myChart").css('display','') ;

                        if(data[0].length > 10){
                            $("#result").addClass('scroll');
                        }

                        var content;
                        content += '<tbody>'
                        $.each(data[0], function(i, val){

                            
                            content+='<tr>';
                            content += '<td>'+val.date+'</td>';
                            content += '<td >'+val.category.title+'</td>';
                            content += '<td >'+val.item+'</td>';
                            content += '<td >'+val.details+'</td>';
                            content += '<td >'+val.price+'</td>';
                            content+='</tr>';


                        });
                        content += '</tbody>'
                        

                        var html = '<tr><th>Date</th><th>Category</th><th>Item</th><th>Details</th><th>Price</th>';

                        html+= '</tr>';

                        $('#result').html('<table class="table shadow-lg" ></table>');
                        $(".table").html(html);
                        $(".table").append(content);


                        //chart

                        var data = data[1];
                        var price = [];
                        var title = [];
                        var total = 0;

                        for(var i = 0;  i < data.length; i++) {
                            title.push([data[i]['category']['title']]);
                            price.push([data[i]['price']]);
                            total += data[i]['price'] << 0; //convert the string elements to numerics using '<< 0'

                        }


                        var ctx = document.getElementById("myChart");
                        ctx.width = 500;
                        ctx.height = 400;
                        var myChart = new Chart(ctx, {
                            type: 'pie',
                            data: {
                                labels: title,
                                datasets: [{
                                    data: price,
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 0.2)',
                                        'rgba(54, 162, 235, 0.2)',
                                        'rgba(255, 206, 86, 0.2)',
                                        'rgba(75, 192, 192, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(255, 159, 64, 0.2)'
                                    ],

                                    borderWidth: 1,
                                    fontColor: '#666'


                                }]
                            },
                            options: {

                                title: {
                                    display: true,
                                    text: 'Monthly Total Expenses: '+total,
                                    fontSize: 25,
                                    padding: 20


                                },
                                tooltips:{
                                    enable: true,
                                    bodyFontSize: 20
                                },
                                legend:{
                                    display: true,
                                    position: 'right',
                                    labels:{
                                        fontSize: 10,
                                        fontColor: '#000'
                                    }
                                },
                                layout: {
                                    padding: {
                                        left: 0,
                                        right: 0,
                                        top: 20,
                                        bottom: 20
                                    }
                                }


                            }

                        });


                    }//else end

               });
            }

        });

    </script>
    <script>
        $.list();
        $('#monthly').change(function(){
            $.list();
        });

        $('#month-year').change(function(){
            $.list();
        });

    </script>

@endsection

resources/views/content/show.blade.php
@extends('master_layout.master')
@section('content')

<form>
    <div class="form-group">
        <label for="date" class="font-weight-bold text-danger">DATE</label>
        <p class="font-weight-light">{{ $item->date }}</p>
        <hr>
        {{--  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">  --}}
        
    </div>
    <div class="form-group">
        <label for="category" class="font-weight-bold text-danger">CATEGORY</label>
        <p class="font-weight-light">{{ $item->category->title }}</p>
        <hr>
        {{--  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">  --}}
            
    </div>
    <div class="form-group">
        <label for="item" class="font-weight-bold text-danger">ITEM</label>
        <p class="font-weight-light"> {{ $item->item }}</p>
        <hr>
        {{--  <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">  --}}
    </div>
    <div class="form-group">
        <label for="details" class="font-weight-bold text-danger">DETAILS</label>
        <p class="font-weight-light"> {{ $item->details }}</p>
        <hr>
        
    </div>
    <div class="form-group">
        <label for="price" class="font-weight-bold text-danger">PRICE</label>
        <p class="font-weight-light"> P{{ $item->price }}.00</p>
        <hr>    
    </div>
    
    <a href="/expenses" class="btn btn-primary">Back</a>
    {{--  <button type="submit" class="btn btn-primary">Submit</button>  --}}
</form>
@endsection

resources/views/content/yearly.blade.php
@extends('master_layout.master')
@section('yearly')
    @php
        $current_date = Carbon\Carbon::now()->toDateString();
    @endphp
    <div class="row">
        <div class="form-group col-md-2">
            <label for="" class="font-weight-bold">Select Year</label>
            <select name="year" id="years" class="form-control">
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
            </select>
        </div>
    </div>

    <div id="result"></div>
    <canvas id="mainChart" width="400" height="250"></canvas>

@endsection



@section('script')

    <script>
        $.extend({
            list: function(){
                $.post('/yearly',{_token: $('meta[name=csrf-token]').attr('content'), years:$('#years').val()},function(data){

                    console.log(data);
                    if (data.length == 0) {
                        $("#result").html('No Records Found');
                        $("#result").attr('class','alert alert-info');
                        $("#mainChart").css('display','none');

                    }else{

                        $("#result").removeAttr('class');
                        $("#mainChart").css('display','') ;

                        //chart for sidebar-right

                        var data = data;
                        var price = [];
                        var month = [];
                        var total = 0;
                        var year = $('#years').val();

                        for(var i = 0;  i < data.length; i++) {
                            month.push([data[i]['month']]);
                            price.push([data[i]['price']]);
                            total += data[i]['year_price'] << 0; //convert the string elements to numerics using '<< 0'

                        }

                        var ctx = document.getElementById("mainChart");
                        ctx.width = 500;
                        ctx.height = 300;
                        var myChart = new Chart(ctx, {
                            type: 'line',

                            data: {
                                labels: month,
                                datasets: [{
                                    label: year,
                                    data: price,
                                    borderColor: "#80b6f4",
                                    borderWidth: 2,
                                    fontColor: '#666',
                                    pointBorderWidth: 5,
                                    pointHoverBorderWidth: 1,
                                    fill: true


                                }]
                            },
                            options: {

                                title: {
                                    display: true,
                                    text: years+' Total Expenses: P'+total,
                                    fontSize: 25,
                                    padding: 10


                                },
                                tooltips:{
                                    enable: true,
                                    bodyFontSize: 15,
                                    titleFontSize: 15
                                },
                                legend:{


                                    labels:{
                                        fontSize: 15,
                                        fontColor: '#000',


                                    }
                                },
                                layout: {
                                    padding: {
                                        left: 0,
                                        right: 0,
                                        top: 20,
                                        bottom: 20
                                    }
                                },
                                scales: {
                                    yAxes:
                                    [{
                                        ticks: {
                                            fontColor: "rgba(0,0,0,0.5)",
                                            fontStyle: "bold",
                                            beginAtZero: true,
                                            maxTicksLimit: 10,
                                            padding: 0
                                        },
                                        gridLines: {
                                            drawTicks: false,
                                            display: true
                                        }
                                    }],
                                    xAxes:
                                    [{
                                        gridLines: {
                                            zeroLineColor: "transparent"
                                            },
                                        ticks: {
                                            padding: 3,
                                            fontColor: "rgba(0,0,0,0.5)",
                                            fontStyle: "bold"
                                        }
                                    }]
                                }


                            }

                        });


                    }//else end

               });
            }

        });

    </script>
    <script>
        $.list();
        $('#years').change(function(){
            $.list();
        });

    </script>

@endsection