routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// login google
// Route::get('/redirect', 'Auth\LoginController@redirectToProvider');
// Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

//login facebook
Route::get('/redirect', 'Auth\SocialAuthFacebookController@redirect');
Route::get('/callback', 'Auth\SocialAuthFacebookController@callback');

// Route::post('login', 'API\UserController@login');
// Route::post('register', 'API\UserController@register');

// Route::group(['middleware' => 'auth:api'], function(){
//     Route::post('details', 'API\UserController@details');
// });

Route::get('/', function(){
    return view ('welcome');
    if(\Auth::check()){
    	return \Redirect::to('/home');

    }
    return \Redirect::to('/login');


});


/* Expenses */
Route::resource('expenses', 'ExpensesController');


/* Category */
Route::resource('category', 'CategoryController');



/* Daily */

Route::get('daily','ByDateController@daily');
Route::post('daily','ByDateController@daily_filter');

/* Weekly */
Route::get('weekly','ByDateController@weekly');
Route::post('weekly','ByDateController@weekly_filter');

/* Monthly */
Route::get('monthly','ByDateController@monthly');
Route::post('monthly','ByDateController@monthly_filter');

/* Yearly */
Route::get('yearly','ByDateController@yearly');
Route::post('yearly','ByDateController@yearly_filter');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/master_layout/footer.blade.php
<p>&copy; tuazonpred@gmail.com</p>

resources/views/master_layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="{{ asset('css/datepicker.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}" type="text/css">
    {{--  <link href="{{ asset('font-awesome/css/all.css') }}" rel="stylesheet">  --}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <title>Budget</title>
</head>
<body>
    <div class="main-page" id="app">

        <header>
            @include('master_layout.navbar')

        </header>
        <section id="income-box">
            @include('content.income')
        </section>
        <section id="sidebar-left">
            @include('master_layout.sidebar-left')
        </section>

        <main>
            @yield('yearly')

            @yield('content')
        </main>
        <section id="sidebar-right">
            @yield('sidebar')
        </section>


        <footer>
            @include('master_layout.footer')
        </footer>

    </div>

    <script src="{{ asset('js/app.js') }}"></script>

    <script type="text/javascript" src="{{ URL::to('js/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('js/Chartjs/Chart.js') }}"></script>
    {{--  <script defer src="{{ asset('font-awesome/js/all.js') }}"></script>   --}}

    @yield('script')
    <script>

        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',

        });

    </script>

</body>
</html>

resources/views/master_layout/navbar.blade.php
<div id="logo">
    
    <a href="" id="side"><img src="{{ asset('images/logo.png') }}" alt="Logo"></a>
    
</div>
<div id="menu">
    <ul>
        <li><a href="">Dashboard</a></li>
        <li><a href="/expenses">Budget</a></li>
        
        
    </ul>
</div>

<div id="sign">
    <ul>
        <li class="nav-item dropdown">
                <a id="" >
                   {{ Auth::user()->name }}
                </a>

        </li>
        <li class="nav-item">
            <a href="{{ route('logout') }}"
                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
                
        </li>
        
    </ul>   
</div> 

resources/views/master_layout/sidebar-left.blade.php
{{--  <ul>

    <li><a href="/expenses">All</a></li>
    <li><a href="/daily">Daily</a></li>
    <li><a href="/weekly">Weekly</a></li>
    <li><a href="/monthly">Monthly</a></li>
    <li><a href="/yearly">Yearly</a></li>

</ul>  --}}



    <ul class="nav nav-pills">
		<li class="nav-item header ">
			<a class="" href=""> Menu Header</a>
			<hr>
		</li>
        <li class="nav-item ">
			<a class="" href="{{ route('category.index') }}"><i class="fas fa-grip-horizontal "></i> Category</a>
        </li>
        <li class="nav-item ">
				<a class=" " href="{{ route('expenses.index') }}"><i class="fas fa-grip-horizontal "></i> All</a>
            {{--  <a class="nav-link active" href="#">Active</a>  --}}
        </li>
        <li class="nav-item " >
            <a class="" href="/daily"> <i class="fas fa-grip-horizontal "></i>Daily</a>
        </li>
        <li class="nav-item">
            <a class=" " href="/weekly"><i class="fas fa-grip-horizontal "></i>Weekly</a>
        </li>
        <li class="nav-item">
            <a class=" " href="/monthly"><i class="fas fa-grip-horizontal "></i>Monthly</a>
        </li>
        <li class="nav-item">
            <a class=" " href="/yearly"><i class="fas fa-grip-horizontal "></i>Yearly</a>
        </li>
    </ul>